import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const sketch = readFileSync(resolve(here, '../code/tiltalert.ino'), 'utf8');
const core = readFileSync(resolve(here, '../code/TiltAlertCore.h'), 'utf8');
const flattened = sketch.replace('#include "TiltAlertCore.h"', core);
if (flattened === sketch) throw new Error('TiltAlertCore.h include not found');
writeFileSync(resolve(here, 'wokwi/sketch.ino'),
  '// GENERATED by node simulation/generate-wokwi.mjs from code/. Do not edit.\n' + flattened);
