// GENERATED by node simulation/generate-wokwi.mjs from code/. Do not edit.
#ifndef TILT_ALERT_CORE_H
#define TILT_ALERT_CORE_H

#include <stdint.h>

// Pure C++ state machine; no Arduino dependency, so transitions can be tested
// with synthetic inputs before uploading to an Uno.
namespace tiltalert {

static const uint8_t kThreshold = 5;
static const uint32_t kTiltDebounceMs = 40;
static const uint32_t kButtonDebounceMs = 35;

struct Events {
  bool tiltRecorded;
  bool alarmStarted;
  bool reset;
};

class DebouncedInput {
 public:
  explicit DebouncedInput(uint32_t intervalMs)
      : intervalMs_(intervalMs), raw_(false), stable_(false), changedAt_(0) {}

  void begin(bool value, uint32_t now) {
    raw_ = value;
    stable_ = value;
    changedAt_ = now;
  }

  bool update(bool value, uint32_t now) {
    if (value != raw_) {
      raw_ = value;
      changedAt_ = now;
    }
    if (stable_ != raw_ && static_cast<uint32_t>(now - changedAt_) >= intervalMs_) {
      stable_ = raw_;
      return true;
    }
    return false;
  }

  bool stable() const { return stable_; }

 private:
  uint32_t intervalMs_;
  bool raw_;
  bool stable_;
  uint32_t changedAt_;
};

class Controller {
 public:
  Controller()
      : tilt_(kTiltDebounceMs), button_(kButtonDebounceMs),
        count_(0), alarm_(false), started_(false) {}

  void begin(uint32_t now, bool tiltHigh, bool buttonPressed) {
    tilt_.begin(tiltHigh, now);
    button_.begin(buttonPressed, now);
    count_ = 0;
    alarm_ = false;
    started_ = true;
  }

  Events update(uint32_t now, bool tiltHigh, bool buttonPressed) {
    Events events = {false, false, false};
    if (!started_) return events;

    const bool tiltChanged = tilt_.update(tiltHigh, now);
    const bool buttonChanged = button_.update(buttonPressed, now);

    // One confirmed press resets a latched alarm. A held button cannot
    // repeatedly reset the counter or acknowledge a later alarm.
    if (buttonChanged && button_.stable() && alarm_) {
      count_ = 0;
      alarm_ = false;
      events.reset = true;
      return events;
    }

    // A cycle means a stable LOW -> HIGH transition. Contact chatter and
    // an initially HIGH sensor are not counted as new inclinations.
    if (tiltChanged && tilt_.stable() && !alarm_) {
      ++count_;
      events.tiltRecorded = true;
      if (count_ >= kThreshold) {
        alarm_ = true;
        events.alarmStarted = true;
      }
    }
    return events;
  }

  uint8_t count() const { return count_; }
  bool alarmActive() const { return alarm_; }

 private:
  DebouncedInput tilt_;
  DebouncedInput button_;
  uint8_t count_;
  bool alarm_;
  bool started_;
};

}  // namespace tiltalert

#endif


// Validated Uno wiring: KY-020 OUT -> D2, KY-012 -> D3,
// red LED -> D13, KY-004 button -> D12 (active LOW).
const uint8_t tiltPin = 2;
const uint8_t buzzerPin = 3;
const uint8_t ledPin = 13;
const uint8_t buttonPin = 12;

tiltalert::Controller controller;

void printEvent(const char* event, uint32_t now) {
  // JSON Lines over USB serial. uptime_ms is time since boot, not a UTC date.
  Serial.print(F("{\"event\":\""));
  Serial.print(event);
  Serial.print(F("\",\"uptime_ms\":"));
  Serial.print(now);
  Serial.print(F(",\"count\":"));
  Serial.print(controller.count());
  Serial.print(F(",\"threshold\":"));
  Serial.print(tiltalert::kThreshold);
  Serial.println(F("}"));
}

void setup() {
  pinMode(tiltPin, INPUT);  // Existing circuit uses an external pull-down.
  pinMode(buttonPin, INPUT_PULLUP);
  pinMode(buzzerPin, OUTPUT);
  pinMode(ledPin, OUTPUT);
  digitalWrite(buzzerPin, LOW);
  digitalWrite(ledPin, LOW);

  Serial.begin(9600);
  const uint32_t now = millis();
  controller.begin(now, digitalRead(tiltPin) == HIGH,
                   digitalRead(buttonPin) == LOW);
  printEvent("ready", now);
}

void loop() {
  const uint32_t now = millis();
  const tiltalert::Events events = controller.update(
      now, digitalRead(tiltPin) == HIGH, digitalRead(buttonPin) == LOW);

  if (events.tiltRecorded) printEvent("tilt", now);
  if (events.alarmStarted) printEvent("alarm", now);
  if (events.reset) printEvent("reset", now);

  const uint8_t output = controller.alarmActive() ? HIGH : LOW;
  digitalWrite(buzzerPin, output);
  digitalWrite(ledPin, output);
}
